sudo: false
language: go
go:
- 1.6.2
install:
- go get -u github.com/kardianos/govendor
- govendor sync
script: go test ./...
deploy:
  provider: heroku
  app: 
    master: snap-plugin-webapi-staging
    production: snap-plugin-webapi
  api_key:
    secure: JdLLK1uBlTxc3rSZDbVysv1hj3E1OwNbJFaouxZjSRv7yX4ONktDrHcTIVDzGZNuj0yu3fkODd/Ax5NJbJgJTsFyAwtTHc5uBHsuMHjemD9YSURbL/ziKkp36nW5U7vRy3B9bOZPkpjKwjE+gwTU3cK73eKXDPJwjOlvaexzWIM6yO0hrAtkIsDxOOQutIpJ70C6SJHvXBA7+o8NyCBM1xdc0+U+L7pSr032Ph+46kO7+Ij7XXXYP43IFoph8U7+Ar/IqjybUshK1vVCS1A4wkwCXjGLUXJ3UIXTj2XFcUGhXlv3iuO2/ZHLiH+afXOjyKTccyjVN8Kl8jgGLsUIjl4BSFLSjxJrC3MXDkZxLdJa5YpzL1PW/LDqPkjO+P9vbTgXSmuwoAWUppvu2IKwu+Pb0ahI8/rpNCZ7DzkItuLAdtiD+4JPyhOkUucN0uvy65HXvQmQjkkEpeAv57abEbnLYDdNQmMxtgvIn71skARb/eqBp8d9B9PPKIq/4e5fqBQGpM1o2iY42sovpOqwh+Dpp4p/1Nm7xD1oiLLCVWX3vvoPqfFNP08vcl+X2mmNNTC5J3ChbywhPKHwNXBxgx2LMuaH3SXLAMEo2LdZI+xDaelX2hL3YP5WWXU8d3YJ4AqUILhhCLKWO81DNcPUYMfeo+u2SFZizLGewtf5cPk=
notifications:
  email: false
  slack:
    secure: ELKEJX9SmlQl/GJM4Azd+KscDyIWYKMFC8hL+Ym38Xu4PWI/z38n7gnhlMrvHbk8CUEfyOu0Tv1TG+u2dH2t9Se39bIg8CJm32B7sG36f3h0uraSK2IMcR3x/58dXihU0I32AANvqv6aweDpO8LVKoTP8h8vIDfvIXBn82vUd+JZha6IeyfpsXXPJ019HjOXaxIU3+DNrnQ28NDLEfZvvAx20kb+WvllUXpCYPyCyMJ0AsW6hFTVeFChy/Fu8mVyZqPMRVilUZcfvTHDLQ91Aa0uMlaaelEq1g0qJ4bRObH73NU7iWQJMzz52jbdm9XSAHEPeU2B8ubmUQckhsGaIBC6qK4mg8mhPDcO1aYop5bZea6eMijgUlfHNyG8LsJedtTs5g+CLm0r99b4QYywt4jHqag/P7sbwS0K/yE5tcRjwJfWdbtx3womMRuAUoL0oqL5l74cTJ9PqvaMguZlo+fbHdFNW+ixeIjQZDwzycub8rgHhQPbM2cVTvDBgliHZKBcy45fpl9donA1OrVSrG3mR+9OlH4mhenDfjXjqlDL3umEuMT3nMySf4SEGHQXBJaEHiI8L/kMQ8HTpVCaSyvcfzzhHgdJ8SATRVOV+YWK4dV+LjAbCCdpIomI4Qd0Fz+JIMGap45Kk8u/ItxYhgsfbuSqTIS6Y8qIS8OhNm8=
